SELECT * FROM
	(SELECT ROWNUM R, D.* FROM 
		(SELECT * FROM SCHEDULE WHERE SCHEDULE_USER_ID='test01'
			ORDER BY SCHEDULE_NUM DESC) D) B
		 WHERE B.R BETWEEN 0 AND 5

SELECT * FROM
	(SELECT ROWNUM R, D.* FROM 
		(SELECT * FROM SCHEDULE WHERE SCHEDULE_OPEN_CHECK=0
			ORDER BY SCHEDULE_NUM DESC) D) B
		 WHERE B.R BETWEEN 0 AND 5
		 
SELECT * FROM
	(SELECT ROWNUM R, D.* FROM 
		(SELECT * FROM SCHEDULE ORDER BY SCHEDULE_NUM DESC) D) B
		 WHERE B.R BETWEEN 0 AND 5
		 
SELECT * FROM "USER";		 
		 
INSERT INTO HR.SCHEDULE
(SCHEDULE_NUM, SCHEDULE_NAME, SCHEDULE_USER_ID, SCHEDULE_CITY_NUM, SCHEDULE_DEPARTURE, SCHEDULE_ARRIVAL, SCHEDULE_TERM, SCHEDULE_OPEN_CHECK, SCHEDULE_VIEWS)
VALUES(SCHEDULE_SEQ.NEXT_VAL, '', 'im1004', 0, '', '', 0, '0', 0);

